[TH2-4989] Transport protocol
th2-net/th2-sim pull request #44
Opened 2023-10-10 11:27 UTC by lumber1000

2023-10-12 10:01 UTC, Nikita-Smirnov-Exactpro requested changes

2023-10-12 10:01 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/sim/impl/Simulator.java
>                          if (logger.isWarnEnabled()) {
Redundant check

2023-10-12 10:01 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/sim/impl/SimulatorRuleInfo.java
> +    public void handle(ParsedMessage message) {
```suggestion
    public void handle(@NotNull ParsedMessage message) {
```

2023-10-12 10:01 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/sim/impl/SimulatorRuleInfo.java
> +        if (group.getMessages().isEmpty()) {
Please add warn log

2023-10-12 10:01 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/sim/impl/SimulatorRuleInfo.java
>              return;
Please add warn log

2023-10-12 10:01 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/sim/impl/SimulatorRuleInfo.java
> +        scheduledExecutorService.schedule(() -> send(toBatch(checkGroup(group), bookName, "")), delay, timeUnit);
Maybe execute checkGroup before schedule

2023-10-12 10:01 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/sim/impl/SimulatorRuleInfo.java
>              return;
Please print wran log here and other similar cases in this class

2023-10-12 10:01 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/sim/run/SimulatorServerMain.java
>              }
```suggestion
            try {
                server.close();
            } catch (Exception e) {
                LOGGER.error("Close gRPC server failure", e);
            }
            try {
                factory.close();
            } catch (Exception e) {
                LOGGER.error("Close common factory failure", e);
            }
```

2023-10-12 10:01 UTC, Nikita-Smirnov-Exactpro commented on src/testFixtures/kotlin/com/exactpro/th2/sim/template/rule/test/api/TestRuleContext.kt
> +    @Deprecated("Deprecated in Java")
Why we added this annotation?

2023-10-12 12:13 UTC, OptimumCode requested changes

2023-10-12 12:13 UTC, OptimumCode commented on src/main/java/com/exactpro/th2/sim/impl/SimulatorRuleInfo.java
> +    public void send(ParsedMessage.@NotNull FromMapBuilder msg) {
Please, correct formatting for the parameter annotation

2023-10-12 12:13 UTC, OptimumCode commented on src/main/java/com/exactpro/th2/sim/impl/SimulatorRuleInfo.java
> +        send((Message<?>) msg);
I think you can name `sendInternal` and avoid explicit casting

2023-10-12 12:13 UTC, OptimumCode commented on src/main/java/com/exactpro/th2/sim/impl/SimulatorRuleInfo.java
> +        }
Why is the eventID for the message required?

2023-10-12 12:13 UTC, OptimumCode commented on src/main/java/com/exactpro/th2/sim/impl/SimulatorRuleInfo.java
> +        if (builder.getEventId() == null) {
Unfortunately, this will throw an exception for RawMessage.Builder because the auto-generated builder does that. We need to modify common lib in order to use the getter like this

2023-10-12 12:13 UTC, OptimumCode commented on src/main/java/com/exactpro/th2/sim/impl/SimulatorRuleInfo.java
> +        if (idBuilder.getSessionAlias().isEmpty()) {
Same here, if the session alias is not set yet an exception will be thrown.
https://github.com/google/auto/blob/main/value/userguide/autobuilder.md#getters

We can either add `is` method or add a getter that returns `Optional` type

2023-10-13 06:40 UTC, Nikita-Smirnov-Exactpro requested changes

2023-10-13 06:40 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/sim/impl/SimulatorRuleInfo.java
> +        var isSessionAliasMissing = message.getId().getSessionAlias().isEmpty();
This check can be failure. Please look at the 
https://github.com/th2-net/th2-conn-sailfish/commit/e359362df8d9507c4eee3e900ab102479076eac7

2023-10-13 07:34 UTC, lumber1000 commented on src/main/java/com/exactpro/th2/sim/impl/SimulatorRuleInfo.java
> +        var isSessionAliasMissing = message.getId().getSessionAlias().isEmpty();
We can't check a field of builder, but we can check a field of message. That's why I've added `var message = builder.build();` here.

2023-10-13 09:16 UTC, OptimumCode commented on src/main/java/com/exactpro/th2/sim/impl/SimulatorRuleInfo.java
> +        var isSessionAliasMissing = message.getId().getSessionAlias().isEmpty();
@lumber1000 Session alias is a required field for MessageID. If we call build without a session alias set we will get an exception (as far as I can see it)

2023-10-18 10:08 UTC, OptimumCode approved these changes

2023-10-18 10:23 UTC, merged