[TS-361] And turn off strategy for default rules
th2-net/th2-sim pull request #6
Opened 2021-01-27 08:43 UTC by Ilya-Loginov-Exactpro

2021-01-27 12:53 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/sim/impl/Simulator.java
>                  logger.warn("Removed default rule with id = {}", id.getId());
!!! This is a fatal problem because we deleted the rule from the `ruleIds` but didn't change the `countDefaultRules`.

2021-01-27 12:53 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/sim/impl/Simulator.java
> +        boolean useDefault = strategy != DefaultRulesTurnOffStrategy.ON_ADD || countDefaultRules.get() == ruleIds.size();
`countDefaultRules.get() == ruleIds.size()` isn't stable approuch, maybe make separate collection for default rules instead counter.

2021-01-27 12:53 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/sim/impl/Simulator.java
> +            if (!useDefault && triggeredRule.isDefault()) {
Double-check is not an explicit decision. Prepared `triggeredRules` will look better

2021-01-27 12:53 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/sim/impl/Simulator.java
> +                    logger.trace("Rule with id '{}' generate messages '{}'", triggeredRule.getId(), builder.toString());
Please extract to a separate function.

2021-01-27 12:53 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/sim/impl/Simulator.java
>              }
Please extract to a separate function.

2021-01-27 13:18 UTC, Ilya-Loginov-Exactpro commented on src/main/java/com/exactpro/th2/sim/impl/Simulator.java
> +        boolean useDefault = strategy != DefaultRulesTurnOffStrategy.ON_ADD || countDefaultRules.get() == ruleIds.size();
It we use new collection with only default rules, we will not any changes for this place. Default rules added only on start, so counter will be change too rarely. We can use `<=` instead `==`

2021-01-27 13:24 UTC, Ilya-Loginov-Exactpro commented on src/main/java/com/exactpro/th2/sim/impl/Simulator.java
> +            if (!useDefault && triggeredRule.isDefault()) {
We can use Stream API for filter and iteration on collection, but we can not write to logger. We need double check, because on step when we generate `triggeredRules` we can add default rule, after that we can add not-default rule. If we use not Stream API or collect filter result to new collection I think, we can lost many performance.

2021-01-27 16:37 UTC, Nikita-Smirnov-Exactpro approved these changes
Please add information about configuration into README.

2021-01-28 10:13 UTC, jean-michel-perli-sonsin commented on README.md
> +Contains settings for the Simulator \
**It** contains **the** settings for **Simulator** \

2021-01-28 10:14 UTC, jean-michel-perli-sonsin commented on README.md
> +Field `strategyDefaultRules` can take values `ON_ADD`, `ON_TRIGGER`.
**The field** `strategyDefaultRules` can take **the** values `ON_ADD` **or** `ON_TRIGGER`.

2021-01-28 10:14 UTC, jean-michel-perli-sonsin commented on README.md
> +Default value is `ON_TRIGGER`.
**The default** value is **set to** `ON_TRIGGER`.

2021-01-28 10:15 UTC, jean-michel-perli-sonsin commented on README.md
> +If you set value `ON_ADD`, the default rules will be disabled If user adds non-default rule.
If you **set the value to** `ON_ADD`, the default rules will be disabled If **an** user adds non-default rule.

2021-01-28 10:18 UTC, jean-michel-perli-sonsin commented on README.md
> +If you set value `ON_TRIGGER`, the default rules will be disabled If non-default rules trigger on the same message. \
If you **set the value to** `ON_TRIGGER`, the default rules will be disabled If non-default rules **will be triggered** on the same message. \

2021-01-28 10:23 UTC, jean-michel-perli-sonsin requested changes
Hi, please review the comments that I made regarding some phrases and correct them accordingly. Thanks

2021-01-28 10:43 UTC, jean-michel-perli-sonsin requested changes
Please review lines 3 to 19 from README.md according to the comments below and see if you agree with them (I was not able to add a comment at those lines for some unknown reason):

The Simulator is **a** service **used to** simulate different **logics**.
All **the logic** **is contained inside** Rule. 
You can turn on/off rules for **one connection or for different connections**.
This project is **based on** java framework **,so it is possible to create a custom Simulator** 
## Interfaces
### ISimulator
**The main** interface of simulator, which contains **the logic** for managing rules and **handle messages** 
### ISimulatorServer
**The interface used** for managing gRPC server
### ISimulatorPart
**The interface used** for gRPC services **to create** Rules
## Settings
**The simulator** using schema api for settings. \
Requirements: ``rabbitMq.json``, ``mq.json``, ``grpc.json`` (server only), ``custom.json`` (optional) 
#### Pins in MessageRouter
**Simulator** subscribe message batches from pins with **the** attributes: ``first``, ``subscribe``, ``parsed`` \
Simulator sends message bathes to pins with **the** attributes ``second``, ``publish``, ``parsed`` and which name session alias \

2021-01-28 11:05 UTC, jean-michel-perli-sonsin approved these changes
All the changes were corrected accordingly.

2021-01-28 11:34 UTC, Nikita-Smirnov-Exactpro approved these changes

2021-01-28 11:46 UTC, merged